### ISSUE TITLE
Signup page did not work properly

### ISSUE THREAD

**Issue by alexsonphoenix** [justdjango/django-ecommerce#23]

**Comment by alexsonphoenix** [comment]
![image](https://user-images.githubusercontent.com/43697906/77816772-6e38c200-712a-11ea-9e08-f17c88f25d4f.png)

**Comment by alexsonphoenix** [comment]
hello, please have a look at this. Thank youuu

**Comment by edgebasis** [comment]
this is because of the email backend of django. When a use signs up django admin sends an email and right now you don't have it.
I would suggest find any free email provider and put this text in the /settings/development.py file in the main app.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_HOST_USER = 'mail@yourdomain.com'
EMAIL_HOST_PASSWORD = 'yourpassword'
DEFAULT_FROM_EMAIL = "mail@yourdomain.com"
EMAIL_PORT = 587

the emails must work otherwise django is going to complain

**Comment by alexsonphoenix** [comment]
thank you so much, I am just wondering if the codes are still usable for django 3.0?

**Comment by edgebasis** [comment]
Not really sure. This was fir django 2.2.2

**Comment by sanketnetalkar** [comment]
> this is because of the email backend of django. When a use signs up django admin sends an email and right now you don't have it.
> I would suggest find any free email provider and put this text in the /settings/development.py file in the main app.
> 
> EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
> EMAIL_USE_TLS = True
> EMAIL_HOST = 'smtp.zoho.com'
> EMAIL_HOST_USER = '[mail@yourdomain.com](mailto:mail@yourdomain.com)'
> EMAIL_HOST_PASSWORD = 'yourpassword'
> DEFAULT_FROM_EMAIL = "[mail@yourdomain.com](mailto:mail@yourdomain.com)"
> EMAIL_PORT = 587
> 
> the emails must work otherwise django is going to complain
Can you suggest any free email providers? and guide on how to do it.

**Comment by sanketnetalkar** [comment]
can you suggest any free email providers? and guide on how to do it.

**Comment by edgebasis** [comment]
I use zoho. For few users they are good.
