### ISSUE TITLE
put footer at the bottom of the page, not fixed

### ISSUE THREAD

**Issue by csyjin6** [justdjango/django-ecommerce#39]
example when clicking "log in", the footer is at the middle of the page. how to fix this?

**Comment by shodown96** [comment]
Have you tried using css to address it,
something like:

`.footer{
  bottom:0;
  right:0;
  left:0;
  position:absolute / fixed;
`

**Comment by csyjin6** [comment]
hi shodown! do you know which css file i should put that in? im confused as to where i should put it. thank you!
![image](https://user-images.githubusercontent.com/57386183/85914985-208d3c00-b876-11ea-8d62-fa72f8788556.png)


> Have you tried using css to address it?,
> something like:
> 
> `.footer{ bottom:0; right:0; left:0; position:absolute / fixed; `

**Comment by shodown96** [comment]
Um you'd wanna put it in the style.css since its gonna override the rest but you will have to change the link reference in the base.html to style.css and not style.min.css except you want to go through a lot of non-spaced code to attach it

<img width="564" alt="Screenshot 2020-06-27 at 9 09 46 PM" src="https://user-images.githubusercontent.com/41167893/85931215-90bdb100-b8ba-11ea-81d2-acb3d3dadb5e.png">


<img width="564" alt="Screenshot 2020-06-27 at 9 12 04 PM" src="https://user-images.githubusercontent.com/41167893/85931252-e42fff00-b8ba-11ea-91a1-9e6e0a89c375.png">
